version: '3'
services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: 'password'
      MYSQL_DATABASE: owlog
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - '13306:3306'
  redis:
    image: redis
    ports:
      - '16379:6379'
